### ISSUE TITLE
Ability to specify a single file directly (similar to httpfs)

### ISSUE THREAD

**Issue by breisig** [fangfufu/httpdirfs#86] opened 2021-08-25 15:17 UTC
Is it possible to add the functionality to be able to show just 1 file instead of a directory file listing in a mounted path? I have a ISO file in a path that doesn't support web directory file listing and would like to be able to mount and show only that ISO file if I specify it directly.

Example.

httpdirfs --no-range-check https://www.example.com/mycrazypath/rocky-linux-8.iso /cdrom/

And it should should show
ls /cdrom/*
rocky-linux-8.iso

**Comment by fangfufu** [comment] 2021-08-31 13:01
@breisig , implemented via https://github.com/fangfufu/httpdirfs/commit/f42264d3c32c8fa513ba0950f7c6711dff3a60ce. Please have a try, and let me know what you think. If you like it, please spread good words of this software! :slightly_smiling_face:

**Comment by WizzardSK** [comment] 2024-04-06 17:41
Please, how to mount the file with url containing spaces? when I mounted in escaped format, the file name is escaped too and cannot be opened in OS. When I provide URL non excaped, it does not mount (Error:src/network.c:163:curl_process_msgs: 3 - URL using bad/illegal format or missing URL)

**Comment by fangfufu** [comment] 2024-04-07 12:03
Re-opened the ticket - will investigate.

**Comment by WizzardSK** [comment] 2024-04-09 12:09
It seems that the problem is only present when I am using --cache, what is the most of times. Otherwise mounting of files with spaces in name (%20) works fine, but it is of course slow without cache.

**Comment by fangfufu** [comment] 2024-04-09 20:35
Yes, the filename resolution has two paths. Because I wrote them at different times, and I wasn't good with software engineer (I probably still am not.) My team mate would call this "skills issue". 

@EyitopeIO Could you propose a fix please? :P

**Comment by EyitopeIO** [comment] 2024-04-16 08:09
Hey, @WizzardSK 
This is now WIP and should have been fixed in a few days.

**Comment by fangfufu** [comment] 2024-04-20 16:21
Closing this issue as the original request had been completed. @WizzardSK , in future please open new issues for bugs, rather than commenting on old feature request issues. :)

**Closed by fangfufu** 2024-04-20 16:21 UTC
Labels: enhancement
