### ISSUE TITLE
Crashes with "API function called from within callback"

### ISSUE THREAD

**Issue by jcharaoui** [fangfufu/httpdirfs#40] opened 2019-08-30 17:37 UTC
I tagged 1.1.8 and readied a package for upload. Before sending the package to the archive I always test it. After a few minutes of streaming a MKV movie file, I get this crash:

`transfer_blocking(): 8, API function called from within callback`

This happened 3 times back to back with different video files.

The mount was configured with default settings (no cache).

**Comment by fangfufu** [comment] 2019-08-30 18:32
Could you give me access to that server and that MKV file, please? Could you also let me know which program you used to play that MKV file, please? Please feel free to send me an email at fangfufu2003@gmail.com, if you don't fancy sending me anything in public.

**Comment by fangfufu** [comment] 2019-08-30 22:19
Okay, can you run it with ``-f``, and give me the full log please? I can't reproduce it, but I have a good idea what might have caused it. The same file segment might have been requested twice by two different threads. 

@jcharaoui , could you reproduce this problem in the older version? I wonder why it didn't show up before.

**Comment by jcharaoui** [comment] 2019-08-31 01:38
@fangfufu I'll send you a full log with `-f` ASAP. I'm positive this never happened with the current Debian version, 1.0.1. We'd have to bisect the repository to see which commit introduced the problem.

**Comment by fangfufu** [comment] 2019-08-31 07:20
I believe I have solved the problem in commit d6fbcb41136f8bdee48e6e244e79ae298b8756a9. 

If you look at the code in v1.0.1, curl handles would not have been added when transfers are happening, due to the mutexes.

https://github.com/fangfufu/httpdirfs/blob/527cad6eaa2a5c93e0bd6ad54bd2da1bf7910aa5/src/network.c#L271-L273

I removed those mutexes, because I thought they weren't needed. They only occasionally show up, because it is one of those concurrency bug...

**Comment by fangfufu** [comment] 2019-08-31 07:37
Right, I am confident this is resolved. I have updated the changelog, Makefile, tagged a new version, and created a new release. Feel free to close the issue once you tested it out.

**Comment by fangfufu** [comment] 2019-08-31 11:44
Okay, I cannot reproduce the exact bug in 1.1.8, even after the trying to use your server. However, I can confirm that 1.1.8 hangs when there are multiple simultaneous I/O requests. I basically ran three instances of ``pv $VIDEO_FILENAME > /dev/null``, 1.1.8 hangs after like 5 minutes. 1.1.9 works fine. 

Previously in order to test my code, I mounted Debian CD image server, ran one instance of ``cat $ISO_FILENAME > /dev/null``, it worked fine. So I thought my code worked fine. 

I guess in future we need to come up with a more comprehensive testing regime.

**Comment by fangfufu** [comment] 2019-09-27 23:50
This bug is definitely resolved.

**Closed by fangfufu** 2019-09-27 23:50 UTC
Labels: bug, regression
